6CS012 Worksheet 0 – Review on Python Programming and NumPy for Deep Learning
Name: Monika Kaphle
Student ID: 2408878
Module: 6CS012 – Artificial Intelligence and Machine Learning

In [ ]:
# Task 1
def unit_converter():
    """
    Converts between length, weight, and volume units.

    The user selects the type of conversion and inputs a value.
    The function performs the conversion and returns the result.

    Returns:
        float: converted value
    """

    try:
        print("Choose conversion type:")
        print("1. Length")
        print("2. Weight")
        print("3. Volume")

        choice = input("Enter choice (1/2/3): ")

        value = float(input("Enter value to convert: "))

        if choice == "1":
            print("1. Meters to Feet")
            print("2. Feet to Meters")
            opt = input("Choose option: ")

            if opt == "1":
                result = value * 3.28084
                print("Result:", result, "ft")

            elif opt == "2":
                result = value / 3.28084
                print("Result:", result, "m")

            else:
                print("Invalid option")

        elif choice == "2":
            print("1. Kilograms to Pounds")
            print("2. Pounds to Kilograms")
            opt = input("Choose option: ")

            if opt == "1":
                result = value * 2.20462
                print("Result:", result, "lbs")

            elif opt == "2":
                result = value / 2.20462
                print("Result:", result, "kg")

            else:
                print("Invalid option")

        elif choice == "3":
            print("1. Liters to Gallons")
            print("2. Gallons to Liters")
            opt = input("Choose option: ")

            if opt == "1":
                result = value * 0.264172
                print("Result:", result, "gal")

            elif opt == "2":
                result = value / 0.264172
                print("Result:", result, "L")

            else:
                print("Invalid option")

        else:
            print("Invalid choice")

    except ValueError:
        print("Error: Please enter a valid number.")


unit_converter()

Choose conversion type:
1. Length
2. Weight
3. Volume
Enter choice (1/2/3): 3
Enter value to convert: 5
1. Liters to Gallons
2. Gallons to Liters
Choose option: 1
Result: 1.3208600000000001 gal


In [ ]:
# Task 2
def find_sum(numbers):
    """Returns sum of numbers."""
    return sum(numbers)

def find_average(numbers):
    """Returns average of numbers."""
    return sum(numbers) / len(numbers)

def find_max(numbers):
    """Returns maximum number."""
    return max(numbers)

def find_min(numbers):
    """Returns minimum number."""
    return min(numbers)


try:
    nums = list(map(float, input("Enter numbers separated by space: ").split()))

    if len(nums) == 0:
        raise ValueError("Empty list")

    print("Choose operation:")
    print("1. Sum")
    print("2. Average")
    print("3. Maximum")
    print("4. Minimum")

    op = input("Enter choice: ")

    if op == "1":
        print("Sum:", find_sum(nums))
    elif op == "2":
        print("Average:", find_average(nums))
    elif op == "3":
        print("Maximum:", find_max(nums))
    elif op == "4":
        print("Minimum:", find_min(nums))
    else:
        print("Invalid operation")

except ValueError:
    print("Error: Please enter valid numbers.")

Enter numbers separated by space: 5
Choose operation:
1. Sum
2. Average
3. Maximum
4. Minimum
Enter choice: 4
Minimum: 5.0


In [ ]:
# 1 List Manipulation 4.2
def extract_every_other(lst):
    """Return every other element."""
    return lst[::2]

print(extract_every_other([1, 2, 3, 4, 5, 6]))

[1, 3, 5]


In [ ]:
# 2 Slice sublist
def get_sublist(lst, start, end):
    """Return sublist from start to end inclusive."""
    return lst[start:end+1]

print(get_sublist([1, 2, 3, 4, 5, 6], 2, 4))

[3, 4, 5]


In [ ]:
# 3 Reverse list
def reverse_list(lst):
    """Reverse list using slicing."""
    return lst[::-1]

print(reverse_list([1, 2, 3, 4, 5]))

[5, 4, 3, 2, 1]


In [ ]:
# 4 Remove first and last
def remove_first_last(lst):
    """Remove first and last element."""
    return lst[1:-1]

print(remove_first_last([1, 2, 3, 4, 5]))

[2, 3, 4]


In [ ]:
# 5 first n elements
def get_first_n(lst, n):
    """Return first n elements."""
    return lst[:n]

print(get_first_n([1, 2, 3, 4, 5], 3))

[1, 2, 3]


In [ ]:
# 6 last n elements
def get_last_n(lst, n):
    """Return last n elements."""
    return lst[-n:]

print(get_last_n([1, 2, 3, 4, 5], 2))

[4, 5]


In [ ]:
# 7 reverse skip
def reverse_skip(lst):
    """Return every second element from second last backwards."""
    return lst[-2::-2]

print(reverse_skip([1, 2, 3, 4, 5, 6]))

[5, 3, 1]


In [ ]:
# Nested list exercise 4.3
# 1 flatten nested list
def flatten(lst):
    """Flatten nested list."""
    result = []
    for sub in lst:
        result.extend(sub)
    return result

print(flatten([[1, 2], [3, 4], [5]]))

[1, 2, 3, 4, 5]


In [ ]:
# 2 Access nested element
def access_nested_element(lst, indices):
    """Access element using index list."""
    element = lst
    for i in indices:
        element = element[i]
    return element

lst = [[1,2,3],[4,5,6],[7,8,9]]
print(access_nested_element(lst, [1,2]))

6


In [ ]:
# 3 Sum nested
def sum_nested(lst):
    """Sum elements in nested list."""
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)
        else:
            total += item
    return total

print(sum_nested([[1,2],[3,[4,5]],6]))

21


In [ ]:
# 4 remove element
def remove_element(lst, elem):
    """Remove element from nested list."""
    result = []
    for item in lst:
        if isinstance(item, list):
            result.append(remove_element(item, elem))
        elif item != elem:
            result.append(item)
    return result

print(remove_element([[1,2],[3,2],[4,5]], 2))

[[1], [3], [4, 5]]


In [ ]:
# 5 find max
def find_max(lst):
    """Find maximum in nested list."""
    max_val = float("-inf")
    for item in lst:
        if isinstance(item, list):
            max_val = max(max_val, find_max(item))
        else:
            max_val = max(max_val, item)
    return max_val

print(find_max([[1,2],[3,[4,5]],6]))

6


In [ ]:
# 6 count occurance
def count_occurrences(lst, elem):
    """Count element in nested list."""
    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)
        elif item == elem:
            count += 1
    return count

print(count_occurrences([[1,2],[2,3],[2,4]], 2))

3


In [ ]:
# 7 deep flatten
def deep_flatten(lst):
    """Flatten list regardless of depth."""
    result = []
    for item in lst:
        if isinstance(item, list):
            result.extend(deep_flatten(item))
        else:
            result.append(item)
    return result

print(deep_flatten([[[1,2],[3,4]],[[5,6],[7,8]]]))

[1, 2, 3, 4, 5, 6, 7, 8]


In [ ]:
# 8 nested average
def average_nested(lst):
    """Return average of nested list."""
    flat = deep_flatten(lst)
    return sum(flat) / len(flat)

print(average_nested([[1,2],[3,4],[5,6]]))

3.5


TO- DO NUMPY
Problem - 1: Array Creation:




Initialize an empty array with size 2X2.

In [4]:
import numpy as np
#Creating 2*2 array
array = np.zeros((2,2))
print(array)

[[0. 0.]
 [0. 0.]]


In [5]:
#Initializing an all ones array with size 4*2
import numpy as np
array_ones = np.ones((4,2))
print(array_ones)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


return a new array of given shape and type, filled with fill_value hint: np.fill

In [6]:
import numpy as np

# Create an empty array of given shape and type
array = np.empty((3, 4), dtype=int)

# Fill it with 7
array.fill(7)

print(array)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}

In [7]:
import numpy as np

# Example existing array
ori = np.array([[1, 2], [3, 4]])

# Create a zeros array with same shape and type
zeros_array = np.zeros_like(ori)

print(zeros_array)

[[0 0]
 [0 0]]


5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}

In [8]:
import numpy as np

# Example existing array
original_array = np.array([[5, 6], [7, 8]], dtype=int)

# Create an ones array with same shape and type
ones_array = np.ones_like(original_array)

print(ones_array)

[[1 1]
 [1 1]]


6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [9]:
import numpy as np

# Existing list
new_list = [1, 2, 3, 4]

# Convert to NumPy array
array = np.array(new_list)

print(array)
print(type(array))  # Shows that it's a numpy.ndarray

[1 2 3 4]
<class 'numpy.ndarray'>


Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:
Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [10]:
#1
import numpy as np

# Create an array from 10 to 49
array = np.arange(10, 50)

print(array)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [11]:
# 2
import numpy as np

# Create a 1D array from 0 to 8
array_1d = np.arange(9)

# Reshape it to 3x3 matrix
matrix_3x3 = array_1d.reshape(3, 3)

print(matrix_3x3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [12]:
# 3
import numpy as np

# Create a 3x3 identity matrix
identity_matrix = np.eye(3)

print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [13]:
# 4
import numpy as np

# Create a random array of size 30 with values between 0 and 1
random_array = np.random.random(30)

# Find the mean of the array
mean_value = random_array.mean()

print("Random Array:\n", random_array)
print("\nMean of the array:", mean_value)

Random Array:
 [0.2958481  0.41175469 0.99496569 0.58275992 0.3334769  0.83348274
 0.64804557 0.44409703 0.73832924 0.16213369 0.21159752 0.34236432
 0.51554126 0.6970915  0.6138704  0.49427756 0.02675943 0.4558639
 0.12661744 0.03685648 0.7013149  0.7825044  0.85380871 0.6593301
 0.57900071 0.76233816 0.32311974 0.53760897 0.20496167 0.59037684]

Mean of the array: 0.49866991841376795


In [14]:
# 5
import numpy as np

# Create a 10x10 array with random values between 0 and 1
random_array = np.random.random((10, 10))

# Find the minimum value
min_value = random_array.min()

# Find the maximum value
max_value = random_array.max()

print("Random 10x10 Array:\n", random_array)
print("\nMinimum value:", min_value)
print("Maximum value:", max_value)

Random 10x10 Array:
 [[0.14183036 0.00219672 0.54801644 0.26276516 0.00449687 0.02630625
  0.88520184 0.09719355 0.11494041 0.41595449]
 [0.00346922 0.69140023 0.15703386 0.44717128 0.37443045 0.24869655
  0.414178   0.19400348 0.73657123 0.43956244]
 [0.72371085 0.32663831 0.79904537 0.45972904 0.95899881 0.52771251
  0.08281883 0.55315135 0.36125312 0.03431452]
 [0.95874908 0.67544611 0.64834747 0.33700938 0.56640581 0.94557649
  0.1629935  0.78824785 0.26715549 0.72945054]
 [0.2233561  0.24945025 0.87794499 0.56100829 0.18741625 0.32597847
  0.50590876 0.52966927 0.68921057 0.75242077]
 [0.67550497 0.54897685 0.30797739 0.70507702 0.34081464 0.99191969
  0.36418556 0.92011365 0.14510387 0.88421674]
 [0.13056292 0.06871143 0.31536748 0.54279582 0.97921504 0.83634548
  0.85386512 0.76463906 0.70789043 0.63161968]
 [0.91585225 0.99309111 0.80431746 0.98642714 0.23598319 0.593979
  0.02901312 0.03946506 0.45847272 0.98464913]
 [0.92649042 0.43280059 0.99716753 0.35428948 0.96367882 0.50

In [15]:
#6
import numpy as np

# Create a 10x10 array with random values between 0 and 1
random_array = np.random.random((10, 10))

# Find minimum and maximum values
min_value = random_array.min()
max_value = random_array.max()

print("Random 10x10 Array:\n", random_array)
print("\nMinimum value:", min_value)
print("Maximum value:", max_value)

Random 10x10 Array:
 [[0.64390143 0.00203809 0.14430407 0.41773155 0.33731327 0.7105271
  0.466559   0.16096622 0.96236626 0.15494207]
 [0.3721942  0.05344097 0.34089372 0.52965482 0.2435742  0.12555886
  0.18113675 0.66875632 0.82001414 0.27566829]
 [0.99662103 0.63485844 0.04228257 0.7011622  0.00854715 0.15608191
  0.92715718 0.29393931 0.46695102 0.44779558]
 [0.78621905 0.44299574 0.12323242 0.56847854 0.89204217 0.43881036
  0.56428104 0.0726911  0.68754932 0.71780548]
 [0.18405138 0.92244307 0.08526092 0.43488934 0.53318856 0.14076896
  0.1515975  0.81168066 0.68257663 0.37924059]
 [0.03392902 0.08697719 0.23158033 0.69754594 0.12228711 0.10453436
  0.03132716 0.60197171 0.44577551 0.03922438]
 [0.37041662 0.99591514 0.71410873 0.91246711 0.85974059 0.02553258
  0.97531225 0.94268628 0.67675748 0.05424148]
 [0.43628324 0.89711315 0.21286029 0.61915064 0.41271793 0.62557755
  0.50433901 0.51477722 0.20541857 0.16128648]
 [0.90085602 0.14656745 0.01974124 0.06265751 0.98840774 0.0

In [16]:
#7
import numpy as np

# Given array
arr = np.array([1, 2, 0, 0, 4, 0])

# Reverse the array
reversed_arr = arr[::-1]

print("Original array:", arr)
print("Reversed array:", reversed_arr)

Original array: [1 2 0 0 4 0]
Reversed array: [0 4 0 0 2 1]


In [17]:
#8
import numpy as np

# size specify gareko
rows, cols = 5, 5  # 5x5 array

# Create an array of zeros
array = np.zeros((rows, cols), dtype=int)

# Fill the borders with 1s
array[0, :] = 1        # mathi ko top row
array[-1, :] = 1       # bottom row
array[:, 0] = 1        # left column
array[:, -1] = 1       # right column

print(array)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [18]:
#8
import numpy as np

# Create an 8x8 matrix of zeros
checkerboard = np.zeros((8, 8), dtype=int)

# Fill the checkerboard pattern: set 1s on alternating positions
checkerboard[1::2, ::2] = 1  # fill 1s on odd rows, even columns
checkerboard[::2, 1::2] = 1  # fill 1s on even rows, odd columns

print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


6CS012 Worksheet - 0 Siman Giri

Problem - 3: Array Operations:
For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [25]:
import numpy as np

# Given arrays
x = np.array([[1, 2],
              [3, 5]])
y = np.array([[5, 6],
              [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

In [20]:
#addition
sum_xy = x + y
print("Sum of x and y:\n", sum_xy)

Sum of x and y:
 [[ 6  8]
 [10 13]]


In [21]:
#Subtraction
diff_xy = x - y
print("Difference of x and y:\n", diff_xy)

Difference of x and y:
 [[-4 -4]
 [-4 -3]]


In [22]:
#multiplying arrays by integers
mult_x = x * 3
mult_v = v * 5

print("x multiplied by 3:\n", mult_x)
print("v multiplied by 5:\n", mult_v)

x multiplied by 3:
 [[ 3  6]
 [ 9 15]]
v multiplied by 5:
 [45 50]


In [23]:
#squareof each element
square_x = x**2
square_v = v**2

print("Square of x:\n", square_x)
print("Square of v:\n", square_v)

Square of x:
 [[ 1  4]
 [ 9 25]]
Square of v:
 [ 81 100]


In [24]:
#dot product
# Dot product between vectors
dot_vw = np.dot(v, w)

# Dot product between matrix and vector
dot_xv = np.dot(x, v)

# Dot product between two matrices
dot_xy = np.dot(x, y)

print("Dot product v.w:", dot_vw)
print("Dot product x.v:", dot_xv)
print("Dot product x.y:\n", dot_xy)

Dot product v.w: 219
Dot product x.v: [29 77]
Dot product x.y:
 [[19 22]
 [50 58]]


In [26]:
#concatenation
concat_row = np.concatenate((x, y), axis=0)
print("x and y concatenated along rows:\n", concat_row)

x and y concatenated along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]


In [27]:
#Along columns (axis=1) for vectors (need reshaping to 2D):
v_reshaped = v.reshape(-1, 1)
w_reshaped = w.reshape(-1, 1)
concat_col = np.concatenate((v_reshaped, w_reshaped), axis=1)
print("v and w concatenated along columns:\n", concat_col)

v and w concatenated along columns:
 [[ 9 11]
 [10 12]]


In [31]:
#conatenate x and v
try:
    concat_xv = np.concatenate((x, v), axis=0)
     #numpy cannot concatenate arrays with different dimension along the same aixs
except ValueError as e:
 print("Error:", e)

Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


We get an error because x is a 2×2 matrix and v is a 1D vector.
NumPy cannot concatenate arrays with different dimensions along the same axis.
So we reshape v into 2D:

In [33]:
#so we fit it by reshaping v with 2D
v_row = v.reshape(1, -1)  # 1x2
concat_xv_fixed = np.concatenate((x, v_row), axis=0)
print("Concatenated x and reshaped v along rows:\n", concat_xv_fixed)

Concatenated x and reshaped v along rows:
 [[ 1  2]
 [ 3  5]
 [ 9 10]]


Problem - 4: Matrix Operations:
• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)T = BTAT
.

• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” func-
tion of Numpy}

In [34]:
import numpy as np

# Define matrices A and B
A = np.array([[3, 4],
              [7, 8]])
B = np.array([[5, 3],
              [2, 1]])

In [35]:
#1
# Compute inverse of A
A_inv = np.linalg.inv(A)

# Multiply A with its inverse
identity = np.dot(A, A_inv)

print("A · A⁻¹:\n", identity)

A · A⁻¹:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


In [36]:
#2
AB = np.dot(A, B)
BA = np.dot(B, A)

print("A·B:\n", AB)
print("B·A:\n", BA)
print("Are A·B and B·A equal?", np.array_equal(AB, BA))

A·B:
 [[23 13]
 [51 29]]
B·A:
 [[36 44]
 [13 16]]
Are A·B and B·A equal? False


In [37]:
#3
AB_T = np.dot(A, B).T
B_T_A_T = np.dot(B.T, A.T)

print("(A·B)ᵀ:\n", AB_T)
print("Bᵀ·Aᵀ:\n", B_T_A_T)
print("Are they equal?", np.array_equal(AB_T, B_T_A_T))

(A·B)ᵀ:
 [[23 51]
 [13 29]]
Bᵀ·Aᵀ:
 [[23 51]
 [13 29]]
Are they equal? True


In [38]:
#4
# Coefficient matrix
coeff = np.array([[2, -3, 1],
                  [1, -1, 2],
                  [3, 1, -1]])

# Constant matrix
const = np.array([-1, -3, 9])

In [39]:
#using np.invert # Compute inverse of coefficient matrix
coeff_inv = np.linalg.inv(coeff)

# Solve for X
X = np.dot(coeff_inv, const)

print("Solution [x, y, z]:", X)

Solution [x, y, z]: [ 2.  1. -2.]


In [40]:
#using np.linalg.solve
X_solve = np.linalg.solve(coeff, const)
print("Solution using np.linalg.solve:", X_solve)

Solution using np.linalg.solve: [ 2.  1. -2.]
